### ISSUE TITLE
Map rotation

### ISSUE THREAD

**Issue by caacree** [jolavb/Sno_Demo#13]
Make it rotate.

**Comment by jolavb** [comment]
Turns out this is already a default feature in Open Layers. Alt+Shift+Drag will rotate the map. I guess we could put a prompt or something to make that clear?

**Comment by caacree** [comment]
Or see if there's a setting somewhere in the setup that adds a button for it.

**Comment by caacree** [comment]
See if there's a setting to add a button for it, and if not we'll throw it in a "info" section (tooltip or footer at the bottom, etc)

**Comment by jolavb** [comment]
No default button in ol aside from the one that returns the map orientation to 0. I'll add a issue to create a tooltip/instructions somewhere. Closing this one out.
