### ISSUE TITLE
Auto index hydrants by elevation

### ISSUE THREAD

**Issue by caacree** [jolavb/Sno_Demo#16]
Self explanatory

**Comment by jolavb** [comment]
Just pushed code to grab elevation and setState to the elevation branch

1.Added getElevation function to trail utilities
      - takes a set of coordinates, reverses them (since ol switches
      lat/lng around), sends request to mapquest with coordinates.
      -Mapquest returns elevation profile (distance between coordinates
      and elevation of each).
      -Since we intend on just grabbing hydrant elevation one by one
      the elevation profile info isn't needed, but could be useful in the
      future.
    
    2. Call getElevation utility function from Container endDraw function
    when new hydrant is added.
      -Once elevation is returned, sets state with added hydrant elevation.

**Comment by caacree** [comment]
Put it in a PR!

**Comment by jolavb** [comment]
Don't tell me what to do GAWL! JK. Also PR for renaming hydrants based on index is out.

**Comment by jolavb** [comment]
Hydrant names are now based on their trail and elevation. Recalculated every time a new hydrant is added.
