### ISSUE TITLE
Edit Hydrant Data

### ISSUE THREAD

**Issue by caacree** [jolavb/Sno_Demo#22]
Make hydrant data editable (elevation, coords, and name for sure, maybe also attach a gun?)

Probably either a popup or something extending out from whatever menu they click on to select the hydrant.

**Comment by jolavb** [comment]
Have the first peice of this finished, but will need some rework with the introduction of redux

**Comment by jolavb** [comment]
```js

case HYDRANT_DELETED: {
      const hydrantId = action.data.selected;
      if (hydrantId === state.selectedHydrant) {
        return {
          ...state,
          hydrants: state.hydrants.delete(hydrantId)
        };
      }
      return state;

```
This code is being reached but not deleting my hydrant

**Comment by jolavb** [comment]
Above  code was in wrong reducer

**Comment by jolavb** [comment]
Don't forget to find a way to select hydrant when it's dropped.

**Comment by caacree** [comment]
https://github.com/jolavb/Sno_Demo/commit/028aeb47c374e825bbccd6c1f27b7cc0e51577d0

Probably better to keep to PR's instead of committing directly to master, leaves a better trail to look at later. It's still fine to merge fast if you need to.
