### ISSUE TITLE
Match Orphaned Hydrants with new Orphans

### ISSUE THREAD

**Issue by jolavb** [jolavb/Sno_Demo#59]
If a user deletes a trail with hydrants, the orphaned hydrant's style doesn't match newly added unaccociated hydrants.

**Comment by caacree** [comment]
Seems like we should call `updateHydrantFeatures` [here](https://github.com/jolavb/Sno_Demo/blob/master/src/redux/reducers/HydrantReducer.js#L95) after we set the trail to null on the hydrant.

**Comment by jolavb** [comment]
Not sure what's going on but in this code is not updating trail to null, even though it is matching correctly.

```js
const newHydrants = state.hydrants.map(hydrant => {
        if (hydrant.get('trail') === trailId) {
          hydrant.set('trail', null);
          updateHydrantFeatures(hydrant, hydrant.toJS());
        }
        return hydrant;
      });
```

**Comment by jolavb** [comment]
Fixed by creating new object from ummutable
